function(add_sljit_flags)
  if(SLJIT_FOUND)
    cmake_parse_arguments(ADD_SLJIT "" "" "" ${ARGN})
    foreach(_target ${ADD_SLJIT_UNPARSED_ARGUMENTS})
      target_include_directories(${_target} PUBLIC ${SLJIT_INCLUDE_DIRS})
      target_compile_definitions(${_target} PUBLIC SLJIT_CONFIG_AUTO=1)
      target_sources(${_target} PRIVATE "${SLJIT_INCLUDE_DIRS}/sljitLir.c")
    endforeach()
  endif(SLJIT_FOUND)
endfunction(add_sljit_flags)
